# Generated by Django 3.0.4 on 2020-03-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arnie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arnie.Arnia')),
            ],
            options={
                'verbose_name_plural': 'Note',
            },
        ),
    ]
