# Generated by Django 3.0.4 on 2020-03-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('apiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiari.Apiario')),
            ],
            options={
                'verbose_name_plural': 'Arnie',
            },
        ),
    ]
